##################################################################
#              Docker Compose file that starts airflow test              #
##################################################################
version: '3.2'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  # Redis for tests
  redis:
    image: redis:4
    ports:
      - 6379

  airflow:
    build: ./airflow
    restart: "no"
    links:
      - mysql:mysql
      - redis:redis
    depends_on:
      - mysql
      - redis
    ports:
      - 18080:8080
    expose:
      - 8080
    environment:
      - PROJ_LIB=/root/miniconda3/share/proj
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/miniconda3/bin
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - AIRFLOW_HOME=~/airflow/
      - PY_ENV=unittest
    healthcheck:
      test: ['CMD-SHELL', 'curl -I -s -L http://127.0.0.1:8080 || exit 1']
      interval: 5s
      retries: 10
    entrypoint: ''
    command: 
      /opt/wait-for-it.sh mysql:3306 -t 0 -- /opt/airflow_start.sh
    volumes:
      - ./opt:/opt
      - ../airflow:/airflow